global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8000"]
    metrics_path: /metrics

  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:8001"]
    metrics_path: /metrics

  - job_name: risk
    static_configs:
      - targets: ["risk:8002"]
    metrics_path: /metrics

  - job_name: provider-adapter
    static_configs:
      - targets: ["provider-adapter:8003"]
    metrics_path: /metrics

  - job_name: ledger
    static_configs:
      - targets: ["ledger:8004"]
    metrics_path: /metrics

  - job_name: notification
    static_configs:
      - targets: ["notification:8005"]
    metrics_path: /metrics
